### ISSUE TITLE
No Method 'find' in class ZerigoDNS::Zone

### ISSUE THREAD

**Issue by JustonDavies** [8x8Cloud/zerigodns#25]
Trying to do a find_by_domain (which is just a wrapper for find) an exception is thrown stating the class has no find method. I am using the 'zerigodns' gem version 1.1.0 on MRI 2.2.0. Let me know what other information you might need.

``` ruby
~$ irb
2.2.0 :001 > require 'zerigodns'
 => true 
2.2.0 :002 > ZerigoDNS::Zone.find_by_domain('skeletor.sexy')
NoMethodError: undefined method `find' for ZerigoDNS::Zone:Class
    from /usr/local/rvm/gems/ruby-2.2.0@ivy/gems/zerigodns-1.1.0/lib/zerigodns/zone.rb:17:in `find_by_domain'
    from (irb):2
    from /usr/local/rvm/rubies/ruby-2.2.0/bin/irb:11:in `<main>'
2.2.0 :003 > 
```

**Comment by raymond-wells** [comment]
Thank you for reporting this bug.  I'm investigating it, but having some trouble with reproducing it.  There could be a difference in our environments causing the issue.

Could you post the operating system, and version of ruby you are running?

**Comment by JustonDavies** [comment]
As stated above, I am using MRI Ruby version 2.2.0 under RVM with 'zerigodns' gem version 1.1.0 on Debian 8.0.

If I do the following I can reproduce the issue.

``` ruby
~$ rvm use 2.2@zerigo_test --create
ruby-2.2.0 - #gemset created /usr/local/rvm/gems/ruby-2.2.0@zerigo_test
ruby-2.2.0 - #generating zerigo_test wrappers..........
Using /usr/local/rvm/gems/ruby-2.2.0 with gemset zerigo_test
~$ gem install zerigodns
Fetching: multi_xml-0.5.5.gem (100%)
Successfully installed multi_xml-0.5.5
Fetching: multipart-post-2.0.0.gem (100%)
Successfully installed multipart-post-2.0.0
Fetching: faraday-0.9.1.gem (100%)
Successfully installed faraday-0.9.1
Fetching: zerigodns-1.1.0.gem (100%)
Successfully installed zerigodns-1.1.0
Parsing documentation for multi_xml-0.5.5
Installing ri documentation for multi_xml-0.5.5
invalid options: -SHN
(invalid options are ignored)
Parsing documentation for multipart-post-2.0.0
Installing ri documentation for multipart-post-2.0.0
Parsing documentation for faraday-0.9.1
Installing ri documentation for faraday-0.9.1
Parsing documentation for zerigodns-1.1.0
Installing ri documentation for zerigodns-1.1.0
Done installing documentation for multi_xml, multipart-post, faraday, zerigodns after 0 seconds
4 gems installed
~$ irb
2.2.0 :001 > require 'zerigodns'
 => true 
2.2.0 :002 > ZerigoDNS::Zone.find_by_domain('skeletor.sexy')
ZerigoDNS::Client::ResponseError: HTTP Response Error: 401
    from /usr/local/rvm/gems/ruby-2.2.0@zerigo_test/gems/zerigodns-1.1.0/lib/zerigodns/middleware/error_handler.rb:16:in `block in call'
    from /usr/local/rvm/gems/ruby-2.2.0@zerigo_test/gems/faraday-0.9.1/lib/faraday/response.rb:57:in `on_complete'
    from /usr/local/rvm/gems/ruby-2.2.0@zerigo_test/gems/zerigodns-1.1.0/lib/zerigodns/middleware/error_handler.rb:11:in `call'
    from /usr/local/rvm/gems/ruby-2.2.0@zerigo_test/gems/zerigodns-1.1.0/lib/zerigodns/middleware/xml.rb:12:in `call'
    from /usr/local/rvm/gems/ruby-2.2.0@zerigo_test/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:56:in `call'
    from /usr/local/rvm/gems/ruby-2.2.0@zerigo_test/gems/faraday-0.9.1/lib/faraday/request/url_encoded.rb:15:in `call'
    from /usr/local/rvm/gems/ruby-2.2.0@zerigo_test/gems/faraday-0.9.1/lib/faraday/request/multipart.rb:14:in `call'
    from /usr/local/rvm/gems/ruby-2.2.0@zerigo_test/gems/zerigodns-1.1.0/lib/zerigodns/middleware/zerigo_auth.rb:14:in `call'
    from /usr/local/rvm/gems/ruby-2.2.0@zerigo_test/gems/faraday-0.9.1/lib/faraday/rack_builder.rb:139:in `build_response'
    from /usr/local/rvm/gems/ruby-2.2.0@zerigo_test/gems/faraday-0.9.1/lib/faraday/connection.rb:377:in `run_request'
    from /usr/local/rvm/gems/ruby-2.2.0@zerigo_test/gems/faraday-0.9.1/lib/faraday/connection.rb:140:in `get'
    from /usr/local/rvm/gems/ruby-2.2.0@zerigo_test/gems/zerigodns-1.1.0/lib/zerigodns/client.rb:62:in `block (2 levels) in singleton class'
    from /usr/local/rvm/gems/ruby-2.2.0@zerigo_test/gems/zerigodns-1.1.0/lib/zerigodns/resource/rest.rb:36:in `find'
    from /usr/local/rvm/gems/ruby-2.2.0@zerigo_test/gems/zerigodns-1.1.0/lib/zerigodns/zone.rb:17:in `find_by_domain'
    from (irb):2
    from /usr/local/rvm/rubies/ruby-2.2.0/bin/irb:11:in `<main>'
2.2.0 :003 > 
```

**Comment by raymond-wells** [comment]
> 2.2.0 :002 > ZerigoDNS::Zone.find_by_domain('skeletor.sexy')
> ZerigoDNS::Client::ResponseError: HTTP Response Error: 401

HTTP Response Error:  401 is returned by the server when the api key & username are not accepted by the server.

Can you check your `api_key` and `user` configuration and make sure they match what you have in the portal?  (please do not post your key here though).

For reference you can find the API key in the `Preferences` section of the DNS portal.

![screen shot 2015-02-23 at 11 51 13](https://cloud.githubusercontent.com/assets/7105019/6335732/5ccb0dae-bb52-11e4-8dae-cdce15b2a6d7.png)

And the instructions to configure the gem are here:

https://github.com/8x8Cloud/zerigodns#how-to-set-up

**Comment by JustonDavies** [comment]
Sorry, I removed the bit with my API key for security reasons. I retried the steps listed above and was able to reproduce the original error:

``` ruby
NoMethodError: undefined method `find' for ZerigoDNS::Zone:Class
    from /usr/local/rvm/gems/ruby-2.2.0@ivy/gems/zerigodns-1.1.0/lib/zerigodns/zone.rb:17:in `find_by_domain'
    from (irb):2
    from /usr/local/rvm/rubies/ruby-2.2.0/bin/irb:11:in `<main>'
```

I destroyed the whole gemset and reinstalled the gem. I noticed a code change in module ZerigoDNS::Resource::Rest introducing a new method 'find'

``` ruby
# Puts a basic resource abstraction over basic REST calls.
module ZerigoDNS::Resource::Rest
  module InstanceMethods

    # Update this instance's resource with attributes supplied into +params+
    # @param [Hash] params The attributes to set
    # @return [Object] The instance on which +update+ was called
    def update params
      self.class.update id, params
      merge_attributes params
      self
    end

    # Destroy this instance's resource
    # @param [Hash] params The attributes to set
    # @raise [ZerigoDNS::Client::ResponseError] if delete does not succeed.
    # @return [Faraday::Response] The response returned from the server.
    def destroy params={}
      self.class.destroy id, params
    end
  end

  module ClassMethods

    # Lists all resources
    # @return [Array] The resources as an array
    def all params={}
      process_response get("#{base_path}.xml", params)
    end

    # Find a single resource
    # @param [Object] id_or_name The id or name of the resource to find
    # @raise [ZerigoDNS::Client::ResponseError] if the find does not succeed.
    # @return [Object] The requested resource.
    def find id_or_name, params={}
      process_response get("#{base_path}/#{id_or_name}.xml", params)
    end

    # Updates a single resource
    # @param [Object] id_or_name Id or name of the resource
    # @raise [ZerigoDNS::Client::ResponseError] if update does not succeed.
    # @return [Faraday::Response] The response returned by the server.
    def update id_or_name, params={}
      put "#{base_path}/#{id_or_name}.xml", convert(params)
    end

    # Creates a resource
    # @param [Object] params Parameters to pass to create action
    # @raise [ZerigoDNS::Client::ResponseError] if create does not succeed.
    # @return [Object] the created resource
    def create params={}
      process_response(post "#{base_path}.xml", convert(params))
    end

    # Deletes a resource
    # @param [Object] params Parameters to pass to delete action
    # @raise [ZerigoDNS::Client::ResponseError] if destroy does not succeed.
    def destroy id_or_name, params={}
      delete "#{base_path}/#{id_or_name}.xml", params
    end


    private

    # Converts a resource object to a hash.
    # @param [Object] object to convert to a hash
    # @raise [ArgumentError] if the object given does not respond to to_hash
    def convert object
      return {resource_name => object} if object.is_a? Hash
      {resource_name =>  object.to_hash}
    end

  end

  def self.included includer
    includer.send :include, InstanceMethods
    includer.send :extend, ClassMethods
  end
end  
```

The old code read

``` ruby
# Puts a basic resource abstraction over basic REST calls.
module ZerigoDNS::Resource::Rest
  module InstanceMethods

    # Update this instance's resource with attributes supplied into +params+
    # @param [Hash] params The attributes to set
    # @return [Object] The instance on which +update+ was called
    def update params
      self.class.update id, params
      merge_attributes params
      self
    end

    # Destroy this instance's resource
    # @param [Hash] params The attributes to set
    # @raise [ZerigoDNS::Client::ResponseError] if delete does not succeed.
    # @return [Faraday::Response] The response returned from the server.
    def destroy params={}
      self.class.destroy id, params
    end
  end

  module ClassMethods

    # Lists all resources
    # @return [Array] The resources as an array
    def all params={}
      process_response get("#{base_path}.xml", params)
    end

    # Find a single resource
    # @param [Object] id_or_name The id or name of the resource to find
    # @raise [ZerigoDNS::Client::ResponseError] if the find does not succeed.
    # @return [Object] The requested resource.
    def   id_or_name params={}
      process_response get("#{base_path}/#{id_or_name}.xml", params)
    end

    # Updates a single resource
    # @param [Object] id_or_name Id or name of the resource
    # @raise [ZerigoDNS::Client::ResponseError] if update does not succeed.
    # @return [Faraday::Response] The response returned by the server.
    def update id_or_name, params={}
      put "#{base_path}/#{id_or_name}.xml", convert(params)
    end

    # Creates a resource
    # @param [Object] params Parameters to pass to create action
    # @raise [ZerigoDNS::Client::ResponseError] if create does not succeed.
    # @return [Object] the created resource
    def create params={}
      process_response(post "#{base_path}.xml", convert(params))
    end

    # Deletes a resource
    # @param [Object] params Parameters to pass to delete action
    # @raise [ZerigoDNS::Client::ResponseError] if destroy does not succeed.
    def destroy id_or_name, params={}
      delete "#{base_path}/#{id_or_name}.xml", params
    end


    private

    # Converts a resource object to a hash.
    # @param [Object] object to convert to a hash
    # @raise [ArgumentError] if the object given does not respond to to_hash
    def convert object
      return {resource_name => object} if object.is_a? Hash
      {resource_name =>  object.to_hash}
    end

  end

  def self.included includer
    includer.send :include, InstanceMethods
    includer.send :extend, ClassMethods
  end
end  
```

I think the issue was on my side, maybe I pulled bogus sources or something got minced post-install. Thanks for the quick response, removing and re-installing the gem worked.
